#!/usr/bin/env bash

session=$(find ~/code -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -d -s "$session_name" -c "$session"
fi

tmux new-session -A -s "$session_name"

# zellij attach -c "$session_name"
#
# if zellij ls "$session_name" 2> /dev/null; then 
#   zellij action write-chars "cd /home/slothy/code/$session_name" && zellij action write 10
# fi
