#!/bin/bash


instances=$(pidof -x "/home/slothy/.config/i3/final" | wc -w)

if [ $instances -gt 2 ] ; then 
  pkill -9 -f ~/.config/i3/final 
fi


max_volume=80
my_headphone="bluez_output.99_67_2E_C6_BF_24.1"
headphone_id=$(pactl list sinks short | grep -i $my_headphone | awk '{print $1}')

# Function to adjust volume if it exceeds the maximum limit
adjust_volume() {
 if [ -n "$headphone_id" ]; then
  [[ $(pactl get-sink-volume $headphone_id | grep -i 'volume' | awk '{gsub(/%/, "", $5); print $5}') -gt max_volume ]] && pactl set-sink-volume $headphone_id $max_volume%
  else
    [[ $(pactl get-sink-volume @DEFAULT_SINK@ | grep -i 'volume' | awk '{gsub(/%/, "", $5); print $5}') -gt max_volume ]] && pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
fi
}

pactl subscribe | grep --line-buffered "sink" | while read -r line; do
    adjust_volume
done
